#!/bin/bash 

if [[ $# -eq 1 ]]; then
    if [[ $1 -eq "list" ]]; then
        selected=$(tmux ls 2>/dev/null | fzf --border --reverse --height 50% --border-label=' Choose a session ')
        selected_name=$(echo $selected | cut -d':' -f1)
    else
        selected=$1
        selected_name=$(basename "$selected" | tr . _)
    fi
else
    selected=$(find ~/FER ~/projects ~/dotfiles ~/learning ~/work -mindepth 1 -maxdepth 1 -type d | fzf)
    selected_name=$(basename "$selected" | tr . _)
fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch -t $selected_name
fi
